version: '3'
services:
    app:
        extra_hosts:
            - "somehost:127.0.0.1"
        build: .
        container_name: elastoo-application
        ports:
            - "3000:8000"
        restart: always